name: Run YouTube API Script

on:
  push:
    branches:
      - main  # Se ejecuta automáticamente al hacer push en la rama 'main'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python get_channel_info.py

      - name: Run script to generate script ideas
        env:
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }}
        run: python generate_script_ideas.py
